# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headers', models.TextField()),
                ('text', models.TextField()),
                ('html', models.TextField()),
                ('to', models.TextField()),
                ('cc', models.TextField()),
                ('subject', models.TextField()),
                ('dkim', jsonfield.fields.JSONField()),
                ('SPF', jsonfield.fields.JSONField()),
                ('envelope', jsonfield.fields.JSONField()),
                ('charsets', models.CharField(max_length=255)),
                ('spam_score', models.FloatField()),
                ('spam_report', models.TextField()),
                ('attachments', models.ManyToManyField(related_name='email', to='django_sendgrid_parse.Attachment')),
            ],
        ),
    ]
