# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_sendgrid_parse.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_sendgrid_parse', '0002_auto_20160729_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='attachments',
        ),
        migrations.AddField(
            model_name='attachment',
            name='email',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='django_sendgrid_parse.Email', verbose_name='Email Attached To'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachment',
            name='number',
            field=models.IntegerField(default=1, verbose_name="Email's Attachment Number"),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=django_sendgrid_parse.models.attachments_file_upload, verbose_name='Attached File'),
        ),
    ]
