# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_sendgrid_parse', '0004_auto_20160816_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='SPF',
            field=models.TextField(blank=True, null=True, verbose_name='Sender Policy Framework'),
        ),
        migrations.AlterField(
            model_name='email',
            name='cc',
            field=models.TextField(blank=True, null=True, verbose_name='Carbon Copy'),
        ),
        migrations.AlterField(
            model_name='email',
            name='dkim',
            field=models.TextField(blank=True, null=True, verbose_name='DomainKeys Identified Mail'),
        ),
        migrations.AlterField(
            model_name='email',
            name='from_mailbox',
            field=models.TextField(verbose_name='From^'),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.TextField(blank=True, null=True, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='email',
            name='to_mailbox',
            field=models.TextField(verbose_name='To^'),
        ),
    ]
