# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_sendgrid_parse', '0005_auto_20160816_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='from_mailbox',
            field=models.TextField(verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='email',
            name='to_mailbox',
            field=models.TextField(verbose_name='To'),
        ),
    ]
