# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_sendgrid_parse', '0006_auto_20160816_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation date'),
            preserve_default=False,
        ),
    ]
