# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 15:49
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_sendgrid_parse', '0007_email_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='envelope',
            field=jsonfield.fields.JSONField(blank=True, default={'from': None, 'to': None}, null=True, verbose_name='Envelope'),
        ),
    ]

